#!/usr/bin/env ruby

ouifile = '/usr/local/pf/conf/allowed_device_oui.txt'

#ouifile = '/PATH/TO/TEST/FILE.txt'

if File.file?(ouifile)

  if ARGV.length >= 2

    newline = "#{ARGV[0]}  # #{ARGV[1]}".to_s.tr('"', '').tr("'", '')

    found_match = false

    count = 1

    matching_line_num = nil

    File.readlines(ouifile).each do |line|
      if line.to_s.tr(' ', '').match(newline.tr(' ', ''))
        found_match = true
        matching_line_num = count
      end
      count = count + 1
    end

    if found_match
      puts "Dup_Error: '#{newline}' is allowed on line '#{matching_line_num}'!"
    else
      open(ouifile, 'a') do |f|
        f << newline + "\n"
      end
      puts "Success: '#{newline}' added to the end of '#{ouifile}'!"
    end

  else
    puts "Arg_Error: Incorrect number of arguments supplied!"
    puts 'Usage: ouiadd 00:00:00 Xbox'
  end

else
  puts "File_Error: #{ouifile.to_s} does not exist!"
end
