#!/usr/bin/env ruby

# Set the OUI file path
#oui_file = '/usr/local/pf/conf/allowed_device_oui.txt'
oui_file = "#{File.expand_path File.dirname(__FILE__)}/oui.txt"

# Does the file exist
if File.file?(oui_file)
  # Did we get enough arguments
  if ARGV.length >= 2
    # form the mac address string
    mac_addr = ARGV[0].to_s.tr('"', '').tr("'", '').upcase
    # form the device label string
    device_label = ARGV[1].to_s.tr('"', '').tr("'", '')
    # form the newline string
    new_line = "#{mac_addr}  # #{device_label}"
    # set the counter
    count = 1
    # iterate over oui file line by line
    File.readlines(oui_file).each do |line|
      # get the line's mac address
      line_mac = line.split('#')[0].to_s.strip
      # does this mac match the one we took in as an argument
      if line_mac.match(mac_addr)
        # exit the program with an error
        puts "Dup_Error: '#{mac_addr}' is already added on line '#{count}'!"
        exit 1
      end
      # increment the line counter
      count = count + 1
    end
    # Open the oui file with append
    open(oui_file, 'a') do |f|
      # write the new line to the file
      f << new_line + "\n"
    end
    # Done
    puts "Success: '#{new_line}' added to the end of '#{oui_file}'!"
  else
    # You need more arguments fool!
    puts "Arg_Error: Incorrect number of arguments supplied!"
    puts 'Usage: ouiadd 00:00:00 Xbox'
    exit 2
  end
else
  # What the heck are you talking about?
  puts "File_Error: #{oui_file.to_s} does not exist!"
  exit 3
end
